version: "3.7"
services:
  backend:
    build: backend
    ports:
      - "8000"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=yes
      - DB_USER=yes
      - DB_PASSWD=yes
#     secrets:
#       - db-password
#     volumes:
#       - ./db/password.txt:/run/secrets/db-password
    depends_on:
      - db
  db:
    image: postgres
    restart: always
#     secrets:
#       - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
#       - ./db/password.txt:/run/secrets/db-password
    environment:
      - POSTGRES_USER=yes
      - POSTGRES_PASSWORD=yes
      - POSTGRES_DB=yes
    
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on: 
      - backend
volumes:
  db-data:
# secrets:
#   db-password:
#     file: db/password.txt
