version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: 'docker-entrypoint.sh --default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - 3306
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  backend:
    depends_on:
      - db
    build: backend
    restart: always
    secrets:
      - db-password
    ports:
      - 5000:5000
    networks:
      - backnet
      - frontnet
  proxy:
    depends_on:
      - backend
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - frontnet
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  backnet:
  frontnet:
